### ISSUE TITLE
Compile time error

### ISSUE THREAD

**Issue by khushDesai** [luiyezheng/JLStickerTextView#14]
Hello, @luiyezheng I have just installed a pods and i got Lots of Errors Please  Check it in Image.
![screen shot 2017-08-21 at 11 33 43 am](https://user-images.githubusercontent.com/29880773/29505589-cf794cc8-8664-11e7-944a-adf7e83a4a04.png)

Please Help What i need to do !
Thanks :)

**Comment by parane** [comment]
I also get different compile time error...xcode 8.2

**Comment by khush004** [comment]
I have Solved this Issue Please find Complete project without errors from https://github.com/khush004/StickerView/tree/master

I have try to pull and push in this project but i didn't have Rights so i have created new repository.
