### ISSUE TITLE
Build Time Error

### ISSUE THREAD

**Issue by khushDesai** [luiyezheng/JLStickerTextView#16]
I am trying to run this project but i got Following Errors.
![screen shot 2017-10-14 at 12 54 01 pm](https://user-images.githubusercontent.com/29880773/31573708-e6cd9e0c-b0de-11e7-9da1-421ebb03186d.png)

**Comment by khush004** [comment]
I have Solved this Issue Please find Complete project without errors from https://github.com/khush004/StickerView/tree/master

I have try to pull and push in this project but i didn't have Rights so i have created new repository.

@luiyezheng  please close this issue

**Comment by Textcat** [comment]
@khush004 Thanks for your contribution ：）
