### ISSUE TITLE
Set image in the background of the Text

### ISSUE THREAD

**Issue by khushDesai** [luiyezheng/JLStickerTextView#22]
I want to set Image as Background of text, is there any way to do that?
Please help!
Thanks.!

**Comment by Textcat** [comment]
I add a `backgroundImage` property to `JLStickerLabelView` which you can use, however, additional codes are required to update the bounds of the background ImageView while the user rotate or drag it. Another option is to use `patternImage`, which is simpler but less flexibility.

```Swift
//Check this out in viewController.swift of Example

//First option, use patternImage
//stickerView.currentlyEditingLabel.backgroundColor = UIColor(patternImage: UIImage(named: "smile")!)
        
//Second option, use UIImageVIew
stickerView.currentlyEditingLabel.backgroundImage = UIImage(named: "smile")

```

**Comment by khushDesai** [comment]
I have used
stickerView.currentlyEditingLabel.backgroundColor = UIColor(patternImage: UIImage(named: "smile")!)

Thanks for your help :)
