### ISSUE TITLE
provide swift 2.3

### ISSUE THREAD

**Issue by mahmoudelfeel** [luiyezheng/JLStickerTextView#6]
not all of us use xcode 8 as it has some issues can you provide swift 2.3 branch

**Comment by kabilya** [comment]
I edited the code for Swift 2.3 as I cannot compile. Let me know if you want it so that I can fork it.

**Comment by mahmoudelfeel** [comment]
yup i want it

**Comment by mahmoudelfeel** [comment]
@kabilya yup been waiting for it for some while

**Comment by kabilya** [comment]
Hi pushed the modified files already. Added a few files as  there are classes that are not yet in Swift 2.3 but only in Swift 3.0, AttributedString.

**Comment by mahmoudelfeel** [comment]
@kabilya Thank You soooo much You,re awesome 😄

**Comment by mahmoudelfeel** [comment]
@kabilya you really did a great job !
if its not too much to ask do you know how to do the same thing but this time add images to the screen?

**Comment by mahmoudelfeel** [comment]
@kabilya  and i also noticed that the text s a little off to the top and isnt centered  in the container which makes some of it get cut
