### ISSUE TITLE
Failed to compile and run the example

### ISSUE THREAD

**Issue by alisa140** [luiyezheng/JLStickerTextView#7]
I tried to compile and run the example. I followed both approach (the manual and the Pod) both were unsuccessful. 

For the Pod attempt, I couldn't pass the error againest import JLStickerTextView, the error is : Cannot load underlying module for 'JLStickerTextView'. I'm using Xcode version 7.3 and used the Example.xcworkspace file. I cleaned and ran again but no luck. My Pod version is the latest and was able to include other pods like SwiftyJSON. 

I even downloaded the Xcode 8 beta 6 to try it, and it was worst because it seems the code is not yet upgraded to swift 3.0 

I'm happy to try anything you may suggest and I'm so greatful for your help
<img width="1018" alt="screen shot 2016-08-20 at 9 41 06 pm" src="https://cloud.githubusercontent.com/assets/20175601/17833193/e6252c5a-671e-11e6-98c1-a3cb2a79e5e8.png">

**Comment by khushDesai** [comment]
@alisa140  You need to check pod file and create New pod file with This project, I have facing same issue i just created new pod file with **pod "JLStickerTextView"** thats it. and my issue is solved. after that i have facing much more compile time errors but my ** Cannot load underlying module for 'JLStickerTextView** error is solved.
